type Data = {
    img: string,
    fistName: string,
    lastName: string,
    desc: string,
    rating: number,
}

export const slideData: Data[] = [
    {
        img: `/homeimg/OperationsDirector.png`,
        fistName: `Michael`,
        lastName: ` Carter`,
        desc: `"The team delivered beyond expectations. Every feature was carefully planned and executed, making our internal systems far more efficient and easier to manage."`,
        rating: 5,
    },
    {
        img: `/homeimg/OperationsDirector.png`,
        fistName: `Emily`,
        lastName: ` Watson`,
        desc: `"Working with this company completely transformed our digital workflow. Communication was smooth, deadlines were respected, and the final product felt premium."`,
        rating: 4,
    },
    {
        img: `/homeimg/OperationsDirector.png`,
        fistName: `Daniel`,
        lastName: ` Brooks`,
        desc: `"Their technical expertise helped us modernize our outdated processes. The attention to detail and commitment to quality were impressive from start to finish."`,
        rating: 5,
    },
    {
        img: `/homeimg/OperationsDirector.png`,
        fistName: `Sophia`,
        lastName: ` Mitchell`,
        desc: `"The platform they built for us is intuitive, reliable, and scalable. Our team adapted quickly thanks to the clean user experience."`,
        rating: 5,
    },
    {
        img: `/homeimg/OperationsDirector.png`,
        fistName: `James`,
        lastName: ` Anderson`,
        desc: `"Excellent service and professional support throughout the project. We especially appreciated their ability to understand our business goals."`,
        rating: 4,
    },
    {
        img: `/homeimg/OperationsDirector.png`,
        fistName: `Olivia`,
        lastName: ` Turner`,
        desc: `"From planning to deployment, the entire process felt organized and transparent. The results exceeded our expectations in every way."`,
        rating: 5,
    },
    {
        img: `/homeimg/OperationsDirector.png`,
        fistName: `Ethan`,
        lastName: ` Hall`,
        desc: `"Their solutions improved our operational efficiency immediately. The support team was responsive and genuinely helpful whenever needed."`,
        rating: 4,
    },
    {
        img: `/homeimg/OperationsDirector.png`,
        fistName: `Charlotte`,
        lastName: ` Evans`,
        desc: `"We were impressed by how quickly they understood our challenges and delivered practical, user-friendly solutions."`,
        rating: 5,
    },
    {
        img: `/homeimg/OperationsDirector.png`,
        fistName: `Benjamin`,
        lastName: ` Lewis`,
        desc: `"The project management and technical implementation were both top-notch. We now have a system that is reliable and future-ready."`,
        rating: 5,
    },
    {
        img: `/homeimg/OperationsDirector.png`,
        fistName: `Ava`,
        lastName: ` Walker`,
        desc: `"Professional, creative, and highly skilled team. They turned our ideas into a polished product that our customers love using."`,
        rating: 5,
    },
]